### PR TITLE
Tweak formatting

### PR DESCRIPTION
**Pull request by cbrnr**
I fixed a typo and removed the 🧠 from the title (looks better without it).

### CODE REVIEW

**Comment by hoechenberger** [comment]
Thanks @cbrnr!

Would you be able to re-run the script (with the MNE sources placed in `../mne-python`) for `mne:main` and add the updated stubs here?

**Comment by cbrnr** [comment]
Done. When building the stubs, I noticed that the following packages were still missing (even though I did `pip install -e ".[dev]"`):

- `pytest`
- `eeglabio`
- `edflib-python`
- `pybv`

It seems like these are not part of `mne[full]`.

Also, I wonder why `edflib-python` is still here. On `main`, I thought we'd replaced it completely with `edfio`...

**Comment by hoechenberger** [comment]
> Also, I wonder why `edflib-python` is still here. On `main`, I thought we'd replaced it completely with `edfio`...

The tool that adds the parameter default values imports `mne`; so I believe that if you still have an older version of MNE installed, it will use that one.

So what you should do before running this script is installing `mne:main`:

```shell
pip install -U ../mne-python
pip install ".[dev]"
python ./gen_type_stubs.py
```

> I noticed that the following packages were still missing

It also seems we need to add `mne[full,dev]` to the `dev` dependencies in `pyproject.toml` here!

**Comment by cbrnr** [comment]
Thanks!

Regarding MNE versions, would it not make sense to generate stubs for the latest release (instead of `main`)?

**Comment by hoechenberger** [comment]
> Regarding MNE versions, would it not make sense to generate stubs for the latest release (instead of `main`)?

Yes absolutely, you're right. We should probably adjust the MNE version pinning accordingly in `pyproject.toml`.

**Comment by hoechenberger** [comment]
Please feel free to take a stab at this

**Comment by hoechenberger** [comment]
If you pull in `main`, the issues discussed above should be resolved

**Comment by hoechenberger** [comment]
Thanks!!

**Pull request merged**
